AEBRequest_PCS.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
CycleTime.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
FPB_Active.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
LDMSelectedController.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
PB_Active.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
PBA_Active.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
PBH_Active.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
PCS_Testmode_Active.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
t_PBA_FPB_PB_PBH_Operation.Toyota_PCS_Common_Timer_FPB_PB_PBA_PBH.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
P_t_PBA_FPB_PB_PBH_Operation_Max nobit 1 unit= scmin=0 scmax=0 
expected_t_PBA_FPB_PB_PBH_Operation.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
sim_t_PBA_FPB_PB_PBH_Operation.TM_Toyota_PCS_Common_Timer_FPB_Calc nobit 1 unit= scmin=0 scmax=0 
